# Generated by Django 4.2.1 on 2023-06-19 09:22

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('waste', '0002_userregistration_delete_user_registration'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='userRegistration',
            new_name='user_Registration',
        ),
    ]
