# Generated by Django 4.2.1 on 2023-06-20 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waste', '0003_rename_userregistration_user_registration'),
    ]

    operations = [
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('rate', models.IntegerField(null=True)),
                ('point', models.IntegerField(null=True)),
                ('desc', models.CharField(max_length=200, null=True)),
                ('image', models.ImageField(null=True, upload_to='')),
                ('status', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
