# Generated by Django 4.2.1 on 2023-07-03 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waste', '0010_collectionhistory_collection_his'),
    ]

    operations = [
        migrations.DeleteModel(
            name='collection_his',
        ),
    ]
