# Generated by Django 4.2.1 on 2023-07-04 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waste', '0011_delete_collection_his'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waste_pickup',
            name='status',
            field=models.CharField(default='requested', max_length=100),
        ),
    ]
