# Generated by Django 4.2.1 on 2023-07-04 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('waste', '0012_alter_waste_pickup_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waste_pickup',
            name='collector',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='waste.collector_registration'),
        ),
    ]
