# Generated by Django 4.2.1 on 2023-07-07 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waste', '0014_remove_waste_pickup_user_waste_pickup_userid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collectionhistory',
            name='user',
        ),
    ]
