# Generated by Django 4.2.1 on 2023-07-17 18:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('waste', '0015_remove_collectionhistory_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, null=True)),
                ('date', models.DateField(verbose_name=django.utils.timezone.now)),
                ('mobile', models.CharField(max_length=100, null=True)),
                ('address', models.CharField(max_length=100, null=True)),
                ('pincode', models.CharField(max_length=20, null=True)),
                ('type', models.CharField(choices=[('R', 'Redeem'), ('P', 'Purchase')], max_length=2)),
                ('status', models.CharField(default='Orderd', max_length=20, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='waste.products')),
            ],
        ),
    ]
