# Generated by Django 4.2.1 on 2023-07-22 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waste', '0021_orderupdates'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderupdates',
            name='status',
            field=models.CharField(default='Ordered', max_length=20, null=True),
        ),
    ]
