# Generated by Django 4.2.1 on 2023-07-23 17:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('waste', '0022_orderupdates_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comaplaints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100, null=True)),
                ('complaint', models.CharField(max_length=200, null=True)),
                ('rdate', models.DateField(default=django.utils.timezone.now)),
                ('sdate', models.DateField(null=True)),
                ('status', models.CharField(default='Pending', max_length=20, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='waste.user_registration')),
            ],
        ),
    ]
