# Generated by Django 4.2.1 on 2023-07-31 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waste', '0023_comaplaints'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='status',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stock_his',
            name='qty',
            field=models.IntegerField(null=True),
        ),
    ]
