# Generated by Django 4.2.1 on 2023-08-05 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waste', '0026_locations'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock_his',
            old_name='qty',
            new_name='stock',
        ),
        migrations.RemoveField(
            model_name='products',
            name='stock',
        ),
        migrations.RemoveField(
            model_name='stock_his',
            name='date',
        ),
    ]
