# Generated by Django 4.2.1 on 2023-08-13 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waste', '0027_rename_qty_stock_his_stock_remove_products_stock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collector_registration',
            name='email',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
